### ISSUE TITLE
config.py中配置参数意义不明

### ISSUE THREAD

**Issue by chengziorange** [misaka7690/HUST-2019-ncov-submit-fucker#1]
family_name = ""
m_uid = ""
m_password = ""
m_qq_pwd = ""

m_sender_email = ""
m_receiver_email = ""

希望能做出一个说明

**Comment by misaka7690** [comment]
加了说明了,不过其实邮箱配起来有点麻烦,要去QQ网页申请一个第三方授权码.
如果不介意每天自动提交的话,可以把whle True那段给注释掉,用最后面的手动提交
