### ISSUE TITLE
2020.5.1 华科登录页面增加了一个验证码

### ISSUE THREAD

**Issue by recolic** [misaka7690/HUST-2019-ncov-submit-fucker#3]
我不确定这是否会影响你的自动填报脚本, 只是提醒一下...
https://git.recolic.net/recolic-hust/hust-2019-ncov-submit-fucker/commit/30e6c197ff1e5b6723d9dc76b1321e95e4014930

**Comment by misaka7690** [comment]
影响了😂

**Comment by misaka7690** [comment]
虽然感觉也可以自动识别验证码,但没精力搞了,现在感觉还是微信填报方便一点....

**Comment by recolic** [comment]
其实我这边还很舒服. 每天在用电脑的时候, 如果看到这个窗口自动弹出, 那就输一下验证码. 其他的也不用人类操作, 还是比微信方便的多的..
